name: UIP
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - cryptography=41.0.3
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pillow=10.0.1
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.10
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aitviewer==1.12.0
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.8
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - bitarray==2.8.5
      - black==23.7.0
      - body-visualizer==1.1.0
      - cachetools==5.3.1
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - chumpy==0.70
      - click==8.1.7
      - coap==1.0.0
      - colorama==0.4.6
      - comm==0.1.4
      - configargparse==1.7
      - contourpy==1.1.0
      - cvxopt==1.3.2
      - cycler==0.11.0
      - cython==3.0.6
      - daqp==0.5.1
      - dash==2.12.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses==0.6
      - decorator==5.1.1
      - ecos==2.0.12
      - executing==1.2.0
      - fairseq==0.12.2
      - fastjsonschema==2.18.0
      - filelock==3.12.4
      - flask==2.2.5
      - fonttools==4.42.1
      - freetype-py==2.4.0
      - fsspec==2023.9.2
      - fvcore==0.1.5.post20221221
      - glcontext==2.5.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - gpytorch==1.11
      - grpcio==1.57.0
      - h5py==3.9.0
      - human-body-prior==2.1.2.0
      - hydra-core==1.0.7
      - imageio==2.31.1
      - imgui==2.0.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.12.2
      - ipywidgets==8.1.0
      - itsdangerous==2.1.2
      - jaxtyping==0.2.19
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - linear-operator==0.5.2
      - lxml==4.9.3
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - matplotlib-label-lines==0.7.0
      - moderngl==5.9.0
      - moderngl-window==2.4.5
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - mxnet-mkl==1.6.0
      - mypy-extensions==1.0.0
      - nbformat==5.7.0
      - nest-asyncio==1.5.7
      - networkx==3.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.0.5
      - open3d==0.17.0
      - opencv-contrib-python-headless==4.8.1.78
      - opencv-python==4.8.0.76
      - osqp==0.6.3
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathspec==0.11.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.10.0
      - plotly==5.16.1
      - portalocker==2.8.2
      - prettytable==3.8.0
      - prompt-toolkit==3.0.39
      - protobuf==4.24.2
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybullet==3.2.5
      - pygame==2.5.1
      - pyglet==2.0.9
      - pygments==2.16.1
      - pyopengl==3.1.0
      - pyparsing==3.0.9
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyquaternion==0.9.9
      - pyrender==0.1.39
      - pyrr==0.10.3
      - python-dateutil==2.8.2
      - python-graphviz==0.8.4
      - pytorch3d==0.7.5
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - qdldl==0.1.7.post0
      - qpsolvers==3.5.0
      - quadprog==0.1.11
      - referencing==0.30.2
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - roma==1.4.1
      - rpds-py==0.9.2
      - rsa==4.9
      - sacrebleu==2.4.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scikit-video==1.1.11
      - scipy==1.10.1
      - scs==3.2.3
      - setuptools==59.5.0
      - smplx==0.1.28
      - stack-data==0.6.2
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tomli==2.0.1
      - torch==1.10.1+cu111
      - torch-geometric==2.4.0
      - torchaudio==0.10.1+cu111
      - torchvision==0.11.2+cu111
      - tqdm==4.66.1
      - traitlets==5.9.0
      - transforms3d==0.4.1
      - trimesh==3.23.5
      - triton==2.1.0
      - typeguard==2.13.3
      - tzdata==2023.3
      - usd-core==23.11
      - vctoolkit==0.1.16.0
      - wcwidth==0.2.6
      - websockets==12.0
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - yacs==0.1.8
      - zipp==3.16.2
